### ISSUE TITLE
Dark mode should respect the user's preference

### ISSUE THREAD

**Issue by chrisvogt** [chrisvogt/gatsby-theme-chrisvogt#53]
Testing via Safari, it doesn't appear that theme-ui is properly respecting the user's color mode preference (via `prefers-color-scheme`). The `localStorage` feature appears to be working correctly, but on initial access the theme is always in light mode. 

Let's fix this so that the initial color mode respects the user's preference the first time they access the site. If they don't have one set, default to dark mode. 🌔

**Comment by GuillouTran** [comment]
@chrisvogt Great idea actually! I hate website having default theme as light
